"""pass 2 billing fields

Revision ID: 28a107b387ce
Revises: a9ca1274bb5c
Create Date: 2026-07-24 13:05:47.782280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28a107b387ce'
down_revision = 'a9ca1274bb5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_charge_id', sa.String(length=64), nullable=True))

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_period_end', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('first_charge_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('pre_charge_reminder_sent_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('pre_charge_reminder_sent_at')
        batch_op.drop_column('first_charge_at')
        batch_op.drop_column('current_period_end')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('stripe_charge_id')

    # ### end Alembic commands ###
