"""pass 4 announcements and outbox retry stamp

Revision ID: 3733d6c3dfdc
Revises: ce3bde95c003
Create Date: 2026-07-24 14:13:41.667789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3733d6c3dfdc'
down_revision = 'ce3bde95c003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_account_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('class_type_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('emailed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_type_id'], ['class_types.id'], ),
    sa.ForeignKeyConstraint(['client_account_id'], ['client_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_announcements_client_account_id'), ['client_account_id'], unique=False)

    with op.batch_alter_table('events_outbox', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_attempt_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events_outbox', schema=None) as batch_op:
        batch_op.drop_column('last_attempt_at')

    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_announcements_client_account_id'))

    op.drop_table('announcements')
    # ### end Alembic commands ###
