"""lead submit ip and user agent

Revision ID: 4ce2fee1a311
Revises: a21df449e449
Create Date: 2026-08-31 19:31:36.644961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ce2fee1a311'
down_revision = 'a21df449e449'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submit_ip', sa.String(length=45), nullable=True))
        batch_op.add_column(sa.Column('submit_user_agent', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_column('submit_user_agent')
        batch_op.drop_column('submit_ip')

    # ### end Alembic commands ###
