"""booking confirmed_at for pre-class check-in

Revision ID: 51508e3568ea
Revises: 626068c467a9
Create Date: 2026-08-20 21:02:42.872022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51508e3568ea'
down_revision = '626068c467a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('confirmed_at')

    # ### end Alembic commands ###
