"""pass 1 full schema

Revision ID: 594526577a6d
Revises: 
Create Date: 2026-07-24 12:29:49.711115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '594526577a6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('commission_rate', sa.Float(), nullable=False),
    sa.Column('timezone', sa.String(length=60), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('site_settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('class_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_account_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('segment_tag', sa.String(length=40), nullable=True),
    sa.Column('age_min', sa.Integer(), nullable=True),
    sa.Column('age_max', sa.Integer(), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('default_capacity', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('accepts_trials', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_account_id'], ['client_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_account_id', 'key', name='uq_class_type_key')
    )
    with op.batch_alter_table('class_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_types_client_account_id'), ['client_account_id'], unique=False)

    op.create_table('closure_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_account_id', sa.Integer(), nullable=False),
    sa.Column('closed_on', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['client_account_id'], ['client_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('closure_dates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_closure_dates_client_account_id'), ['client_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_closure_dates_closed_on'), ['closed_on'], unique=False)

    op.create_table('events_outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_account_id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=80), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_account_id'], ['client_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    with op.batch_alter_table('events_outbox', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_outbox_client_account_id'), ['client_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_outbox_dispatched_at'), ['dispatched_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_outbox_event_name'), ['event_name'], unique=False)

    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_account_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_name', sa.String(length=80), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('quote_text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('segment_tags', sa.String(length=255), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_account_id'], ['client_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_client_account_id'), ['client_account_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_account_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('consent_email', sa.Boolean(), nullable=False),
    sa.Column('consent_sms', sa.Boolean(), nullable=False),
    sa.Column('consent_captured_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('invited_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_account_id'], ['client_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_account_id', 'email', name='uq_user_email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_client_account_id'), ['client_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('waiver_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_account_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('body_md', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_account_id'], ['client_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_account_id', 'kind', 'version', name='uq_waiver_ver')
    )
    with op.batch_alter_table('waiver_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_waiver_documents_client_account_id'), ['client_account_id'], unique=False)

    op.create_table('attendee_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_account_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=120), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('health_json', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_account_id'], ['client_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendee_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendee_profiles_client_account_id'), ['client_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendee_profiles_user_id'), ['user_id'], unique=False)

    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_account_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('segment', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('utm_source', sa.String(length=120), nullable=True),
    sa.Column('utm_medium', sa.String(length=120), nullable=True),
    sa.Column('utm_campaign', sa.String(length=255), nullable=True),
    sa.Column('utm_content', sa.String(length=255), nullable=True),
    sa.Column('utm_term', sa.String(length=255), nullable=True),
    sa.Column('landing_variant', sa.String(length=80), nullable=True),
    sa.Column('first_touch_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_account_id'], ['client_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leads_client_account_id'), ['client_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_segment'), ['segment'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_user_id'), ['user_id'], unique=False)

    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_account_id', sa.Integer(), nullable=False),
    sa.Column('class_type_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('interval', sa.String(length=10), nullable=False),
    sa.Column('stripe_price_id', sa.String(length=64), nullable=True),
    sa.Column('is_placeholder', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['class_type_id'], ['class_types.id'], ),
    sa.ForeignKeyConstraint(['client_account_id'], ['client_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plans_client_account_id'), ['client_account_id'], unique=False)

    op.create_table('stripe_customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=64), nullable=True),
    sa.Column('payment_method_status', sa.String(length=10), nullable=False),
    sa.Column('stripe_setup_intent_id', sa.String(length=64), nullable=True),
    sa.Column('stripe_payment_method_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_customer_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('trainers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_account_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role_title', sa.String(length=120), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=True),
    sa.Column('class_type_keys', sa.JSON(), nullable=True),
    sa.Column('pay_rate_cents', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_account_id'], ['client_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trainers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trainers_client_account_id'), ['client_account_id'], unique=False)

    op.create_table('calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_account_id', sa.Integer(), nullable=False),
    sa.Column('tracking_number', sa.String(length=20), nullable=False),
    sa.Column('caller_number', sa.String(length=20), nullable=False),
    sa.Column('duration_sec', sa.Integer(), nullable=False),
    sa.Column('recording_url', sa.String(length=512), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('matched_lead_id', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['client_account_id'], ['client_accounts.id'], ),
    sa.ForeignKeyConstraint(['matched_lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calls_caller_number'), ['caller_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_calls_client_account_id'), ['client_account_id'], unique=False)

    op.create_table('member_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_account_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('attendee_id', sa.Integer(), nullable=True),
    sa.Column('author_user_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attendee_id'], ['attendee_profiles.id'], ),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_account_id'], ['client_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('member_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_member_notes_client_account_id'), ['client_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_member_notes_user_id'), ['user_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_account_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('attendee_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('template', sa.String(length=120), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body_preview', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('delivery_status', sa.String(length=40), nullable=False),
    sa.Column('unsubscribe_honored', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['attendee_id'], ['attendee_profiles.id'], ),
    sa.ForeignKeyConstraint(['client_account_id'], ['client_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_client_account_id'), ['client_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_user_id'), ['user_id'], unique=False)

    op.create_table('schedule_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_account_id', sa.Integer(), nullable=False),
    sa.Column('class_type_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_time_local', sa.Time(), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('trainer_id', sa.Integer(), nullable=True),
    sa.Column('accepts_trials', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['class_type_id'], ['class_types.id'], ),
    sa.ForeignKeyConstraint(['client_account_id'], ['client_accounts.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedule_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_templates_client_account_id'), ['client_account_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_account_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('attendee_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('mrr_cents', sa.Integer(), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancel_reason', sa.String(length=80), nullable=True),
    sa.Column('cancel_reason_note', sa.Text(), nullable=True),
    sa.Column('paused_at', sa.DateTime(), nullable=True),
    sa.Column('resumes_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attendee_id'], ['attendee_profiles.id'], ),
    sa.ForeignKeyConstraint(['client_account_id'], ['client_accounts.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_subscription_id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_attendee_id'), ['attendee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_client_account_id'), ['client_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_user_id'), ['user_id'], unique=False)

    op.create_table('waiver_signatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attendee_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('signed_by_user_id', sa.Integer(), nullable=False),
    sa.Column('signature_name', sa.String(length=120), nullable=False),
    sa.Column('signed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attendee_id'], ['attendee_profiles.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['waiver_documents.id'], ),
    sa.ForeignKeyConstraint(['signed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('waiver_signatures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_waiver_signatures_attendee_id'), ['attendee_id'], unique=False)

    op.create_table('class_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_account_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('class_type_id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=True),
    sa.Column('starts_at_utc', sa.DateTime(), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('local_time', sa.Time(), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('room', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('accepts_trials', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['class_type_id'], ['class_types.id'], ),
    sa.ForeignKeyConstraint(['client_account_id'], ['client_accounts.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['schedule_templates.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'local_date', name='uq_instance_occurrence')
    )
    with op.batch_alter_table('class_instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_instances_class_type_id'), ['class_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_instances_client_account_id'), ['client_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_instances_local_date'), ['local_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_instances_starts_at_utc'), ['starts_at_utc'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_instances_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_instances_template_id'), ['template_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_account_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('stripe_invoice_id', sa.String(length=64), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('agency_share_cents', sa.Integer(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('refunded_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_account_id'], ['client_accounts.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_invoice_id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_client_account_id'), ['client_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_user_id'), ['user_id'], unique=False)

    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_account_id', sa.Integer(), nullable=False),
    sa.Column('attendee_id', sa.Integer(), nullable=False),
    sa.Column('class_instance_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('booked_at', sa.DateTime(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('late_cancel', sa.Boolean(), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(), nullable=True),
    sa.Column('attendance_marked_by', sa.String(length=120), nullable=True),
    sa.Column('ipad_walkin', sa.Boolean(), nullable=False),
    sa.Column('reminder_24h_sent_at', sa.DateTime(), nullable=True),
    sa.Column('reminder_2h_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attendee_id'], ['attendee_profiles.id'], ),
    sa.ForeignKeyConstraint(['class_instance_id'], ['class_instances.id'], ),
    sa.ForeignKeyConstraint(['client_account_id'], ['client_accounts.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attendee_id', 'class_instance_id', name='uq_booking')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_attendee_id'), ['attendee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_class_instance_id'), ['class_instance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_client_account_id'), ['client_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_status'), ['status'], unique=False)

    op.create_table('waitlist_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_account_id', sa.Integer(), nullable=False),
    sa.Column('class_instance_id', sa.Integer(), nullable=False),
    sa.Column('attendee_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('offered_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attendee_id'], ['attendee_profiles.id'], ),
    sa.ForeignKeyConstraint(['class_instance_id'], ['class_instances.id'], ),
    sa.ForeignKeyConstraint(['client_account_id'], ['client_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('waitlist_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_waitlist_entries_class_instance_id'), ['class_instance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_waitlist_entries_client_account_id'), ['client_account_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waitlist_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_waitlist_entries_client_account_id'))
        batch_op.drop_index(batch_op.f('ix_waitlist_entries_class_instance_id'))

    op.drop_table('waitlist_entries')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_status'))
        batch_op.drop_index(batch_op.f('ix_bookings_client_account_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_class_instance_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_attendee_id'))

    op.drop_table('bookings')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_user_id'))
        batch_op.drop_index(batch_op.f('ix_payments_client_account_id'))

    op.drop_table('payments')
    with op.batch_alter_table('class_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_instances_template_id'))
        batch_op.drop_index(batch_op.f('ix_class_instances_status'))
        batch_op.drop_index(batch_op.f('ix_class_instances_starts_at_utc'))
        batch_op.drop_index(batch_op.f('ix_class_instances_local_date'))
        batch_op.drop_index(batch_op.f('ix_class_instances_client_account_id'))
        batch_op.drop_index(batch_op.f('ix_class_instances_class_type_id'))

    op.drop_table('class_instances')
    with op.batch_alter_table('waiver_signatures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_waiver_signatures_attendee_id'))

    op.drop_table('waiver_signatures')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_status'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_client_account_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_attendee_id'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('schedule_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_templates_client_account_id'))

    op.drop_table('schedule_templates')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_user_id'))
        batch_op.drop_index(batch_op.f('ix_messages_client_account_id'))

    op.drop_table('messages')
    with op.batch_alter_table('member_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_member_notes_user_id'))
        batch_op.drop_index(batch_op.f('ix_member_notes_client_account_id'))

    op.drop_table('member_notes')
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calls_client_account_id'))
        batch_op.drop_index(batch_op.f('ix_calls_caller_number'))

    op.drop_table('calls')
    with op.batch_alter_table('trainers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trainers_client_account_id'))

    op.drop_table('trainers')
    op.drop_table('stripe_customers')
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plans_client_account_id'))

    op.drop_table('plans')
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_user_id'))
        batch_op.drop_index(batch_op.f('ix_leads_status'))
        batch_op.drop_index(batch_op.f('ix_leads_segment'))
        batch_op.drop_index(batch_op.f('ix_leads_phone'))
        batch_op.drop_index(batch_op.f('ix_leads_email'))
        batch_op.drop_index(batch_op.f('ix_leads_client_account_id'))

    op.drop_table('leads')
    with op.batch_alter_table('attendee_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendee_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_attendee_profiles_client_account_id'))

    op.drop_table('attendee_profiles')
    with op.batch_alter_table('waiver_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_waiver_documents_client_account_id'))

    op.drop_table('waiver_documents')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_client_account_id'))

    op.drop_table('users')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_client_account_id'))

    op.drop_table('reviews')
    with op.batch_alter_table('events_outbox', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_outbox_event_name'))
        batch_op.drop_index(batch_op.f('ix_events_outbox_dispatched_at'))
        batch_op.drop_index(batch_op.f('ix_events_outbox_client_account_id'))

    op.drop_table('events_outbox')
    with op.batch_alter_table('closure_dates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_closure_dates_closed_on'))
        batch_op.drop_index(batch_op.f('ix_closure_dates_client_account_id'))

    op.drop_table('closure_dates')
    with op.batch_alter_table('class_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_types_client_account_id'))

    op.drop_table('class_types')
    op.drop_table('site_settings')
    op.drop_table('client_accounts')
    # ### end Alembic commands ###
