"""30-day cancellation notice fields

Revision ID: 626068c467a9
Revises: cb53593435e5
Create Date: 2026-08-20 20:26:22.162368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '626068c467a9'
down_revision = 'cb53593435e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancel_requested_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancel_effective_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('cancel_effective_at')
        batch_op.drop_column('cancel_requested_at')

    # ### end Alembic commands ###
