"""schedule template starts_on (program launch date)

Revision ID: a21df449e449
Revises: f757b8bfd6e0
Create Date: 2026-08-30 16:13:10.985009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a21df449e449'
down_revision = 'f757b8bfd6e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starts_on', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule_templates', schema=None) as batch_op:
        batch_op.drop_column('starts_on')

    # ### end Alembic commands ###
