"""cohort groups on templates, instances, subscriptions

Revision ID: a9ca1274bb5c
Revises: 594526577a6d
Create Date: 2026-07-24 12:45:07.748025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9ca1274bb5c'
down_revision = '594526577a6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cohort_label', sa.String(length=40), nullable=True))
        batch_op.create_index(batch_op.f('ix_class_instances_cohort_label'), ['cohort_label'], unique=False)

    with op.batch_alter_table('schedule_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cohort_label', sa.String(length=40), nullable=True))

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cohort_label', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('cohort_label')

    with op.batch_alter_table('schedule_templates', schema=None) as batch_op:
        batch_op.drop_column('cohort_label')

    with op.batch_alter_table('class_instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_instances_cohort_label'))
        batch_op.drop_column('cohort_label')

    # ### end Alembic commands ###
