"""pass 3 referral codes and notify prefs

Revision ID: ce3bde95c003
Revises: 28a107b387ce
Create Date: 2026-07-24 13:50:29.873281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce3bde95c003'
down_revision = '28a107b387ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referral_code', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_leads_referral_code'), ['referral_code'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referral_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('notify_prefs', sa.JSON(), nullable=True))
        batch_op.create_unique_constraint("uq_users_referral_code", ['referral_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint("uq_users_referral_code", type_='unique')
        batch_op.drop_column('notify_prefs')
        batch_op.drop_column('referral_code')

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_referral_code'))
        batch_op.drop_column('referral_code')

    # ### end Alembic commands ###
