"""booking first_charge_on

Revision ID: e45e37d307f4
Revises: 4ce2fee1a311
Create Date: 2026-09-04 13:02:13.209688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e45e37d307f4'
down_revision = '4ce2fee1a311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_charge_on', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('first_charge_on')

    # ### end Alembic commands ###
