"""payment tax_cents (GST)

Revision ID: f757b8bfd6e0
Revises: 51508e3568ea
Create Date: 2026-08-21 10:18:59.772054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f757b8bfd6e0'
down_revision = '51508e3568ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        # server_default so pre-GST rows read 0, not NULL
        batch_op.add_column(
            sa.Column('tax_cents', sa.Integer(), nullable=False,
                      server_default='0')
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('tax_cents')

    # ### end Alembic commands ###
