"""attendee trial closed

Revision ID: f7d4ce3773b6
Revises: e45e37d307f4
Create Date: 2026-09-08 15:08:31.297339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7d4ce3773b6'
down_revision = 'e45e37d307f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendee_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trial_closed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('trial_closed_reason', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendee_profiles', schema=None) as batch_op:
        batch_op.drop_column('trial_closed_reason')
        batch_op.drop_column('trial_closed_at')

    # ### end Alembic commands ###
